### ISSUE TITLE
Error while trying to establish link

### ISSUE THREAD

**Issue by thiagorroque** [brain-products/LSL-actiCHamp#3]
Hi, 
I'm not been able to use the LSL-actiCHamp software.
The "Scan" feature is working perfectly, but after clicking on "Link" I receive an error saying "Could not initialize the actiCHamp: Error setting trigger output mode, error code: AMP_ERR_NOSUPPORT".
I tried all possible combinations of trigger setup and none of them worked.
I`m using the old version of the actiCHamp (not the plus).

Thank you.

**Comment by dmedine** [comment]
Are you using the latest version (1.15)? https://github.com/brain-products/LSL-actiCHamp/releases/tag/v1.15.0

I don't have a non-plus actiCHamp to test with at the moment, but will investigate.

**Comment by thiagorroque** [comment]
Sorry for my delayed response.
Yes, I'm using the latest version...
Do you have any hint of what might be causing this?
If there is any log files I can send you to help solving this, I'm happy to contribute.

**Comment by dmedine** [comment]
No log file, but the error code was enough for me to pinpoint the bug. I believe I fixed it, but I can't be sure without testing with an old actiCHamp. Can you please try the newest release: https://github.com/brain-products/LSL-actiCHamp/releases/tag/v1.15.1 ? Let me know if it still gives you an error.

**Comment by thiagorroque** [comment]
Great.
I'll be at the lab by the afternoon, once I get there, I'll try it.
Thank you.

**Comment by thiagorroque** [comment]
It worked!
Thank you David.
